server:
  port: 8010
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DB_DATAWAREHOUSE
    username: sa
    password: ${sqlserverpass}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update