server:
  port: 8020

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DB_VIVERO
    username: sa
    password: ${sqlserverpass}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
